services:
  - type: web
    name: fastapi-clientes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: https://api-soporte-default-rtdb.firebaseio.com